### ISSUE TITLE
dom.js in node.js

### ISSUE THREAD

**Issue by yaronn** [andreasgal/dom.js#18]
Hi

I have compiled dom.js and now want to use it in node.js.

How to get started? When I run the generated dom.js in node I get a few errors (const in strict mode, and then Function.prototype not defined...).

Thanks

**Comment by davidflanagan** [comment]
yaronn,

Use 'make domnode.js' to produce a version of dom.js that works (at least somewhat) in node.  
Note, however, that this isn't incredibly well supported yet, so it might not do what you want.

**Comment by yaronn** [comment]
Thanks!

What I am looking for is a way to manipulate xml documents (not html). So I
need to be aware of namespaces, prefixes etc. Is dom.js a good fit here?
I'm ok with bugs I just want to know if in general this is a valid use case.

Yaron

On Mon, Jan 23, 2012 at 7:50 PM, David Flanagan <
reply@reply.github.com

**Comment by ghost** [comment]
I recommend using the Node 0.7 beta and make sure to run node with the command `node --harmony`.
