### ISSUE TITLE
dom.js and Rhino (Java 7 ScriptEngine)

### ISSUE THREAD

**Issue by aeos** [andreasgal/dom.js#22]
Hi,

 when I try to evaluate dom.js using the ScriptEngine in Java, it returns the following exception:

 Property "nodeValue" already defined in this object literal. (<Unknown source>#1131) in <Unknown source> at line number 1131

I was hoping to use dom.js in conjunction with jQuery to do dom manipulation of HTML markup.

**Comment by davidflanagan** [comment]
dom.js was written and tested only on SpiderMonkey. I'm not sure what is happening in the Java-based engine, but I'm guessing there is some incompatibility between the JS implementations.  dom.js uses a number of ES5 and ES6 features, and used those ES6 features before they were completely standardized. For example, dom.js use proxies, but I think it uses an old version of proxies that no longer follow the specification. I doubt that the Java-based JS engine includes that out-of-date version of Proxies.

dom.js is not being actively maintained anymore. You can fork it and try making it work for your needs yourself.  But you might be better off starting with one of the other DOM libraries out there.

**Comment by aeos** [comment]
Hi David,

Thank you for the quick response! I will continue my search for a dom library that will also work with Java's Script Engine.

**Comment by kicOLD** [comment]
please let us know if you were lucky and fnd one!
